//----------------------------------------------------------------------------------------------
// MFTrace.h
//----------------------------------------------------------------------------------------------
#ifndef MFTRACE_H
#define MFTRACE_H

#if (_DEBUG && MF_USE_LOGGING)

inline LPCWSTR MFErrorString(HRESULT hr){
	
	switch(hr){
			
		// General MediaFoudation
		RETURN_STRING(MF_E_PLATFORM_NOT_INITIALIZED);
		RETURN_STRING(MF_E_BUFFERTOOSMALL);
		RETURN_STRING(MF_E_INVALIDREQUEST);
		RETURN_STRING(MF_E_INVALIDSTREAMNUMBER);
		RETURN_STRING(MF_E_INVALIDMEDIATYPE);
		RETURN_STRING(MF_E_NOTACCEPTING);
		RETURN_STRING(MF_E_NOT_INITIALIZED);
		RETURN_STRING(MF_E_UNSUPPORTED_REPRESENTATION);
		RETURN_STRING(MF_E_NO_MORE_TYPES);
		RETURN_STRING(MF_E_UNSUPPORTED_SERVICE);
		RETURN_STRING(MF_E_UNEXPECTED);
		RETURN_STRING(MF_E_INVALIDNAME);
		RETURN_STRING(MF_E_INVALIDTYPE);
		RETURN_STRING(MF_E_INVALID_FILE_FORMAT);
		RETURN_STRING(MF_E_INVALIDINDEX);
		RETURN_STRING(MF_E_INVALID_TIMESTAMP);
		RETURN_STRING(MF_E_UNSUPPORTED_SCHEME);
		RETURN_STRING(MF_E_UNSUPPORTED_BYTESTREAM_TYPE);
		RETURN_STRING(MF_E_UNSUPPORTED_TIME_FORMAT);
		RETURN_STRING(MF_E_NO_SAMPLE_TIMESTAMP);
		RETURN_STRING(MF_E_NO_SAMPLE_DURATION);
		RETURN_STRING(MF_E_INVALID_STREAM_DATA);
		RETURN_STRING(MF_E_RT_UNAVAILABLE);
		RETURN_STRING(MF_E_UNSUPPORTED_RATE);
		RETURN_STRING(MF_E_THINNING_UNSUPPORTED);
		RETURN_STRING(MF_E_REVERSE_UNSUPPORTED);
		RETURN_STRING(MF_E_UNSUPPORTED_RATE_TRANSITION);
		RETURN_STRING(MF_E_RATE_CHANGE_PREEMPTED);
		RETURN_STRING(MF_E_NOT_FOUND);
		RETURN_STRING(MF_E_NOT_AVAILABLE);
		RETURN_STRING(MF_E_NO_CLOCK);
		RETURN_STRING(MF_S_MULTIPLE_BEGIN);
		RETURN_STRING(MF_E_MULTIPLE_BEGIN);
		RETURN_STRING(MF_E_MULTIPLE_SUBSCRIBERS);
		RETURN_STRING(MF_E_TIMER_ORPHANED);
		RETURN_STRING(MF_E_STATE_TRANSITION_PENDING);
		RETURN_STRING(MF_E_UNSUPPORTED_STATE_TRANSITION);
		RETURN_STRING(MF_E_UNRECOVERABLE_ERROR_OCCURRED);
		RETURN_STRING(MF_E_SAMPLE_HAS_TOO_MANY_BUFFERS);
		RETURN_STRING(MF_E_SAMPLE_NOT_WRITABLE);
		RETURN_STRING(MF_E_INVALID_KEY);
		RETURN_STRING(MF_E_BAD_STARTUP_VERSION);
		RETURN_STRING(MF_E_UNSUPPORTED_CAPTION);
		RETURN_STRING(MF_E_INVALID_POSITION);
		RETURN_STRING(MF_E_ATTRIBUTENOTFOUND);
		RETURN_STRING(MF_E_PROPERTY_TYPE_NOT_ALLOWED);
		RETURN_STRING(MF_E_PROPERTY_TYPE_NOT_SUPPORTED);
		RETURN_STRING(MF_E_PROPERTY_EMPTY);
		RETURN_STRING(MF_E_PROPERTY_NOT_EMPTY);
		RETURN_STRING(MF_E_PROPERTY_VECTOR_NOT_ALLOWED);
		RETURN_STRING(MF_E_PROPERTY_VECTOR_REQUIRED);
		RETURN_STRING(MF_E_OPERATION_CANCELLED);
		RETURN_STRING(MF_E_BYTESTREAM_NOT_SEEKABLE);
		RETURN_STRING(MF_E_DISABLED_IN_SAFEMODE);
		RETURN_STRING(MF_E_CANNOT_PARSE_BYTESTREAM);
		RETURN_STRING(MF_E_SOURCERESOLVER_MUTUALLY_EXCLUSIVE_FLAGS);
		RETURN_STRING(MF_E_MEDIAPROC_WRONGSTATE);
		RETURN_STRING(MF_E_RT_THROUGHPUT_NOT_AVAILABLE);
		RETURN_STRING(MF_E_RT_TOO_MANY_CLASSES);
		RETURN_STRING(MF_E_RT_WOULDBLOCK);
		RETURN_STRING(MF_E_NO_BITPUMP);
		RETURN_STRING(MF_E_RT_OUTOFMEMORY);
		RETURN_STRING(MF_E_RT_WORKQUEUE_CLASS_NOT_SPECIFIED);
		RETURN_STRING(MF_E_INSUFFICIENT_BUFFER);
		RETURN_STRING(MF_E_CANNOT_CREATE_SINK);
		RETURN_STRING(MF_E_BYTESTREAM_UNKNOWN_LENGTH);
		RETURN_STRING(MF_E_SESSION_PAUSEWHILESTOPPED);
		RETURN_STRING(MF_S_ACTIVATE_REPLACED);
		RETURN_STRING(MF_E_FORMAT_CHANGE_NOT_SUPPORTED);
		RETURN_STRING(MF_E_INVALID_WORKQUEUE);
		RETURN_STRING(MF_E_DRM_UNSUPPORTED);
		RETURN_STRING(MF_E_UNAUTHORIZED);
		RETURN_STRING(MF_E_OUT_OF_RANGE);
		RETURN_STRING(MF_E_INVALID_CODEC_MERIT);
		RETURN_STRING(MF_E_HW_MFT_FAILED_START_STREAMING);
		// Specific Transform
		RETURN_STRING(MF_E_TRANSFORM_TYPE_NOT_SET);
		RETURN_STRING(MF_E_TRANSFORM_STREAM_CHANGE);
		RETURN_STRING(MF_E_TRANSFORM_INPUT_REMAINING);
		RETURN_STRING(MF_E_TRANSFORM_PROFILE_MISSING);
		RETURN_STRING(MF_E_TRANSFORM_PROFILE_INVALID_OR_CORRUPT);
		RETURN_STRING(MF_E_TRANSFORM_PROFILE_TRUNCATED);
		RETURN_STRING(MF_E_TRANSFORM_PROPERTY_PID_NOT_RECOGNIZED);
		RETURN_STRING(MF_E_TRANSFORM_PROPERTY_VARIANT_TYPE_WRONG);
		RETURN_STRING(MF_E_TRANSFORM_PROPERTY_NOT_WRITEABLE);
		RETURN_STRING(MF_E_TRANSFORM_PROPERTY_ARRAY_VALUE_WRONG_NUM_DIM);
		RETURN_STRING(MF_E_TRANSFORM_PROPERTY_VALUE_OUT_OF_RANGE);
		RETURN_STRING(MF_E_TRANSFORM_PROPERTY_VALUE_INCOMPATIBLE);
		RETURN_STRING(MF_E_TRANSFORM_NOT_POSSIBLE_FOR_CURRENT_OUTPUT_MEDIATYPE);
		RETURN_STRING(MF_E_TRANSFORM_NOT_POSSIBLE_FOR_CURRENT_INPUT_MEDIATYPE);
		RETURN_STRING(MF_E_TRANSFORM_NOT_POSSIBLE_FOR_CURRENT_MEDIATYPE_COMBINATION);
		RETURN_STRING(MF_E_TRANSFORM_CONFLICTS_WITH_OTHER_CURRENTLY_ENABLED_FEATURES);
		RETURN_STRING(MF_E_TRANSFORM_NEED_MORE_INPUT);
		RETURN_STRING(MF_E_TRANSFORM_NOT_POSSIBLE_FOR_CURRENT_SPKR_CONFIG);
		RETURN_STRING(MF_E_TRANSFORM_CANNOT_CHANGE_MEDIATYPE_WHILE_PROCESSING);
		RETURN_STRING(MF_S_TRANSFORM_DO_NOT_PROPAGATE_EVENT);
		RETURN_STRING(MF_E_UNSUPPORTED_D3D_TYPE);
		RETURN_STRING(MF_E_TRANSFORM_ASYNC_LOCKED);
		RETURN_STRING(MF_E_TRANSFORM_CANNOT_INITIALIZE_ACM_DRIVER);
		// Specific Topology
		RETURN_STRING(MF_E_TOPO_INVALID_OPTIONAL_NODE);
		RETURN_STRING(MF_E_TOPO_CANNOT_FIND_DECRYPTOR);
		RETURN_STRING(MF_E_TOPO_CODEC_NOT_FOUND);
		RETURN_STRING(MF_E_TOPO_CANNOT_CONNECT);
		RETURN_STRING(MF_E_TOPO_UNSUPPORTED);
		RETURN_STRING(MF_E_TOPO_INVALID_TIME_ATTRIBUTES);
		RETURN_STRING(MF_E_TOPO_LOOPS_IN_TOPOLOGY);
		RETURN_STRING(MF_E_TOPO_MISSING_PRESENTATION_DESCRIPTOR);
		RETURN_STRING(MF_E_TOPO_MISSING_STREAM_DESCRIPTOR);
		RETURN_STRING(MF_E_TOPO_STREAM_DESCRIPTOR_NOT_SELECTED);
		RETURN_STRING(MF_E_TOPO_MISSING_SOURCE);
		RETURN_STRING(MF_E_TOPO_SINK_ACTIVATES_UNSUPPORTED);
		// Specific Media Source
		RETURN_STRING(MF_E_NO_EVENTS_AVAILABLE);
		RETURN_STRING(MF_E_INVALID_STATE_TRANSITION);
		RETURN_STRING(MF_E_END_OF_STREAM);
		RETURN_STRING(MF_E_SHUTDOWN);
		RETURN_STRING(MF_E_MP3_NOTFOUND);
		RETURN_STRING(MF_E_MP3_OUTOFDATA);
		RETURN_STRING(MF_E_MP3_NOTMP3);
		RETURN_STRING(MF_E_MP3_NOTSUPPORTED);
		RETURN_STRING(MF_E_NO_DURATION);
		RETURN_STRING(MF_E_INVALID_FORMAT);
		RETURN_STRING(MF_E_PROPERTY_NOT_FOUND);
		RETURN_STRING(MF_E_PROPERTY_READ_ONLY);
		RETURN_STRING(MF_E_PROPERTY_NOT_ALLOWED);
		RETURN_STRING(MF_E_MEDIA_SOURCE_NOT_STARTED);
		RETURN_STRING(MF_E_UNSUPPORTED_FORMAT);
		RETURN_STRING(MF_E_MP3_BAD_CRC);
		RETURN_STRING(MF_E_NOT_PROTECTED);
		RETURN_STRING(MF_E_MEDIA_SOURCE_WRONGSTATE);
		RETURN_STRING(MF_E_MEDIA_SOURCE_NO_STREAMS_SELECTED);
		RETURN_STRING(MF_E_CANNOT_FIND_KEYFRAME_SAMPLE);
		// Specific Media Sink
		RETURN_STRING(MF_E_STREAMSINK_REMOVED);
		RETURN_STRING(MF_E_STREAMSINKS_OUT_OF_SYNC);
		RETURN_STRING(MF_E_STREAMSINKS_FIXED);
		RETURN_STRING(MF_E_STREAMSINK_EXISTS);
		RETURN_STRING(MF_E_SAMPLEALLOCATOR_CANCELED);
		RETURN_STRING(MF_E_SAMPLEALLOCATOR_EMPTY);
		RETURN_STRING(MF_E_SINK_ALREADYSTOPPED);
		RETURN_STRING(MF_E_ASF_FILESINK_BITRATE_UNKNOWN);
		RETURN_STRING(MF_E_SINK_NO_STREAMS);
		RETURN_STRING(MF_S_SINK_NOT_FINALIZED);
		RETURN_STRING(MF_E_METADATA_TOO_LONG);
		RETURN_STRING(MF_E_SINK_NO_SAMPLES_PROCESSED);
		// Specific Renderer
		RETURN_STRING(MF_E_VIDEO_REN_NO_PROCAMP_HW);
		RETURN_STRING(MF_E_VIDEO_REN_NO_DEINTERLACE_HW);
		RETURN_STRING(MF_E_VIDEO_REN_COPYPROT_FAILED);
		RETURN_STRING(MF_E_VIDEO_REN_SURFACE_NOT_SHARED);
		RETURN_STRING(MF_E_VIDEO_DEVICE_LOCKED);
		RETURN_STRING(MF_E_NEW_VIDEO_DEVICE);
		RETURN_STRING(MF_E_NO_VIDEO_SAMPLE_AVAILABLE);
		RETURN_STRING(MF_E_NO_AUDIO_PLAYBACK_DEVICE);
		RETURN_STRING(MF_E_AUDIO_PLAYBACK_DEVICE_IN_USE);
		RETURN_STRING(MF_E_AUDIO_PLAYBACK_DEVICE_INVALIDATED);
		RETURN_STRING(MF_E_AUDIO_SERVICE_NOT_RUNNING);
		// Specific Clock
		RETURN_STRING(MF_E_CLOCK_INVALID_CONTINUITY_KEY);
		RETURN_STRING(MF_E_CLOCK_NO_TIME_SOURCE);
		RETURN_STRING(MF_E_CLOCK_STATE_ALREADY_SET);
		RETURN_STRING(MF_E_CLOCK_NOT_SIMPLE);
		RETURN_STRING(MF_S_CLOCK_STOPPED);
		// Specific Quality Management
		RETURN_STRING(MF_E_NO_MORE_DROP_MODES);
		RETURN_STRING(MF_E_NO_MORE_QUALITY_LEVELS);
		RETURN_STRING(MF_E_DROPTIME_NOT_SUPPORTED);
		RETURN_STRING(MF_E_QUALITYKNOB_WAIT_LONGER);
		RETURN_STRING(MF_E_QM_INVALIDSTATE);
		// Specific Dxva2
		RETURN_STRING(DXVA2_E_NOT_INITIALIZED);
		RETURN_STRING(DXVA2_E_NEW_VIDEO_DEVICE);
		RETURN_STRING(DXVA2_E_VIDEO_DEVICE_LOCKED);
		RETURN_STRING(DXVA2_E_NOT_AVAILABLE);
		// Specific Transcode
		RETURN_STRING(MF_E_TRANSCODE_NO_CONTAINERTYPE);
		RETURN_STRING(MF_E_TRANSCODE_PROFILE_NO_MATCHING_STREAMS);
		RETURN_STRING(MF_E_TRANSCODE_NO_MATCHING_ENCODER);
		// Specific ASF Parsing
		RETURN_STRING(MF_S_ASF_PARSEINPROGRESS);
		RETURN_STRING(MF_E_ASF_PARSINGINCOMPLETE);
		RETURN_STRING(MF_E_ASF_MISSINGDATA);
		RETURN_STRING(MF_E_ASF_INVALIDDATA);
		RETURN_STRING(MF_E_ASF_OPAQUEPACKET);
		RETURN_STRING(MF_E_ASF_NOINDEX);
		RETURN_STRING(MF_E_ASF_OUTOFRANGE);
		RETURN_STRING(MF_E_ASF_INDEXNOTLOADED);
		RETURN_STRING(MF_E_ASF_TOO_MANY_PAYLOADS);
		RETURN_STRING(MF_E_ASF_UNSUPPORTED_STREAM_TYPE);
		RETURN_STRING(MF_E_ASF_DROPPED_PACKET);
		// Specific Device Proxy
		RETURN_STRING(MF_E_ALLOCATOR_NOT_INITIALIZED);
		RETURN_STRING(MF_E_ALLOCATOR_NOT_COMMITED);
		RETURN_STRING(MF_E_ALLOCATOR_ALREADY_COMMITED);
		RETURN_STRING(MF_E_STREAM_ERROR);
		RETURN_STRING(MF_E_INVALID_STREAM_STATE);
		RETURN_STRING(MF_E_HW_STREAM_NOT_CONNECTED);
		// Specific Network
		RETURN_STRING(MF_E_NETWORK_RESOURCE_FAILURE);
		RETURN_STRING(MF_E_NET_WRITE);
		RETURN_STRING(MF_E_NET_READ);
		RETURN_STRING(MF_E_NET_REQUIRE_NETWORK);
		RETURN_STRING(MF_E_NET_REQUIRE_ASYNC);
		RETURN_STRING(MF_E_NET_BWLEVEL_NOT_SUPPORTED);
		RETURN_STRING(MF_E_NET_STREAMGROUPS_NOT_SUPPORTED);
		RETURN_STRING(MF_E_NET_MANUALSS_NOT_SUPPORTED);
		RETURN_STRING(MF_E_NET_INVALID_PRESENTATION_DESCRIPTOR);
		RETURN_STRING(MF_E_NET_CACHESTREAM_NOT_FOUND);
		RETURN_STRING(MF_I_MANUAL_PROXY);
		RETURN_STRING(MF_E_NET_REQUIRE_INPUT);
		RETURN_STRING(MF_E_NET_REDIRECT);
		RETURN_STRING(MF_E_NET_REDIRECT_TO_PROXY);
		RETURN_STRING(MF_E_NET_TOO_MANY_REDIRECTS);
		RETURN_STRING(MF_E_NET_TIMEOUT);
		RETURN_STRING(MF_E_NET_CLIENT_CLOSE);
		RETURN_STRING(MF_E_NET_BAD_CONTROL_DATA);
		RETURN_STRING(MF_E_NET_INCOMPATIBLE_SERVER);
		RETURN_STRING(MF_E_NET_UNSAFE_URL);
		RETURN_STRING(MF_E_NET_CACHE_NO_DATA);
		RETURN_STRING(MF_E_NET_EOL);
		RETURN_STRING(MF_E_NET_BAD_REQUEST);
		RETURN_STRING(MF_E_NET_INTERNAL_SERVER_ERROR);
		RETURN_STRING(MF_E_NET_SESSION_NOT_FOUND);
		RETURN_STRING(MF_E_NET_NOCONNECTION);
		RETURN_STRING(MF_E_NET_CONNECTION_FAILURE);
		RETURN_STRING(MF_E_NET_INCOMPATIBLE_PUSHSERVER);
		RETURN_STRING(MF_E_NET_SERVER_ACCESSDENIED);
		RETURN_STRING(MF_E_NET_PROXY_ACCESSDENIED);
		RETURN_STRING(MF_E_NET_CANNOTCONNECT);
		RETURN_STRING(MF_E_NET_INVALID_PUSH_TEMPLATE);
		RETURN_STRING(MF_E_NET_INVALID_PUSH_PUBLISHING_POINT);
		RETURN_STRING(MF_E_NET_BUSY);
		RETURN_STRING(MF_E_NET_RESOURCE_GONE);
		RETURN_STRING(MF_E_NET_ERROR_FROM_PROXY);
		RETURN_STRING(MF_E_NET_PROXY_TIMEOUT);
		RETURN_STRING(MF_E_NET_SERVER_UNAVAILABLE);
		RETURN_STRING(MF_E_NET_TOO_MUCH_DATA);
		RETURN_STRING(MF_E_NET_SESSION_INVALID);
		RETURN_STRING(MF_E_OFFLINE_MODE);
		RETURN_STRING(MF_E_NET_UDP_BLOCKED);
		RETURN_STRING(MF_E_NET_UNSUPPORTED_CONFIGURATION);
		RETURN_STRING(MF_E_NET_PROTOCOL_DISABLED);
		// Specific WMContainer
		RETURN_STRING(MF_E_ALREADY_INITIALIZED);
		RETURN_STRING(MF_E_BANDWIDTH_OVERRUN);
		RETURN_STRING(MF_E_LATE_SAMPLE);
		RETURN_STRING(MF_E_FLUSH_NEEDED);
		RETURN_STRING(MF_E_INVALID_PROFILE);
		RETURN_STRING(MF_E_INDEX_NOT_COMMITTED);
		RETURN_STRING(MF_E_NO_INDEX);
		RETURN_STRING(MF_E_CANNOT_INDEX_IN_PLACE);
		RETURN_STRING(MF_E_MISSING_ASF_LEAKYBUCKET);
		RETURN_STRING(MF_E_INVALID_ASF_STREAMID);
		// Specific Timeline
		RETURN_STRING(MF_E_SEQUENCER_UNKNOWN_SEGMENT_ID);
		RETURN_STRING(MF_S_SEQUENCER_CONTEXT_CANCELED);
		RETURN_STRING(MF_E_NO_SOURCE_IN_CACHE);
		RETURN_STRING(MF_S_SEQUENCER_SEGMENT_AT_END_OF_STREAM);
		// Specific Protection
		RETURN_STRING(MF_E_LICENSE_INCORRECT_RIGHTS);
		RETURN_STRING(MF_E_LICENSE_OUTOFDATE);
		RETURN_STRING(MF_E_LICENSE_REQUIRED);
		RETURN_STRING(MF_E_DRM_HARDWARE_INCONSISTENT);
		RETURN_STRING(MF_E_NO_CONTENT_PROTECTION_MANAGER);
		RETURN_STRING(MF_E_LICENSE_RESTORE_NO_RIGHTS);
		RETURN_STRING(MF_E_BACKUP_RESTRICTED_LICENSE);
		RETURN_STRING(MF_E_LICENSE_RESTORE_NEEDS_INDIVIDUALIZATION);
		RETURN_STRING(MF_S_PROTECTION_NOT_REQUIRED);
		RETURN_STRING(MF_E_COMPONENT_REVOKED);
		RETURN_STRING(MF_E_TRUST_DISABLED);
		RETURN_STRING(MF_E_WMDRMOTA_NO_ACTION);
		RETURN_STRING(MF_E_WMDRMOTA_ACTION_ALREADY_SET);
		RETURN_STRING(MF_E_WMDRMOTA_DRM_HEADER_NOT_AVAILABLE);
		RETURN_STRING(MF_E_WMDRMOTA_DRM_ENCRYPTION_SCHEME_NOT_SUPPORTED);
		RETURN_STRING(MF_E_WMDRMOTA_ACTION_MISMATCH);
		RETURN_STRING(MF_E_WMDRMOTA_INVALID_POLICY);
		RETURN_STRING(MF_E_POLICY_UNSUPPORTED);
		RETURN_STRING(MF_E_OPL_NOT_SUPPORTED);
		RETURN_STRING(MF_E_TOPOLOGY_VERIFICATION_FAILED);
		RETURN_STRING(MF_E_SIGNATURE_VERIFICATION_FAILED);
		RETURN_STRING(MF_E_DEBUGGING_NOT_ALLOWED);
		RETURN_STRING(MF_E_CODE_EXPIRED);
		RETURN_STRING(MF_E_GRL_VERSION_TOO_LOW);
		RETURN_STRING(MF_E_GRL_RENEWAL_NOT_FOUND);
		RETURN_STRING(MF_E_GRL_EXTENSIBLE_ENTRY_NOT_FOUND);
		RETURN_STRING(MF_E_KERNEL_UNTRUSTED);
		RETURN_STRING(MF_E_PEAUTH_UNTRUSTED);
		RETURN_STRING(MF_E_NON_PE_PROCESS);
		RETURN_STRING(MF_E_REBOOT_REQUIRED);
		RETURN_STRING(MF_S_WAIT_FOR_POLICY_SET);
		RETURN_STRING(MF_S_VIDEO_DISABLED_WITH_UNKNOWN_SOFTWARE_OUTPUT);
		RETURN_STRING(MF_E_GRL_INVALID_FORMAT);
		RETURN_STRING(MF_E_GRL_UNRECOGNIZED_FORMAT);
		RETURN_STRING(MF_E_ALL_PROCESS_RESTART_REQUIRED);
		RETURN_STRING(MF_E_PROCESS_RESTART_REQUIRED);
		RETURN_STRING(MF_E_USERMODE_UNTRUSTED);
		RETURN_STRING(MF_E_PEAUTH_SESSION_NOT_STARTED);
		RETURN_STRING(MF_E_PEAUTH_PUBLICKEY_REVOKED);
		RETURN_STRING(MF_E_GRL_ABSENT);
		RETURN_STRING(MF_S_PE_TRUSTED);
		RETURN_STRING(MF_E_PE_UNTRUSTED);
		RETURN_STRING(MF_E_PEAUTH_NOT_STARTED);
		RETURN_STRING(MF_E_INCOMPATIBLE_SAMPLE_PROTECTION);
		RETURN_STRING(MF_E_PE_SESSIONS_MAXED);
		RETURN_STRING(MF_E_HIGH_SECURITY_LEVEL_CONTENT_NOT_ALLOWED);
		RETURN_STRING(MF_E_TEST_SIGNED_COMPONENTS_NOT_ALLOWED);
		RETURN_STRING(MF_E_ITA_UNSUPPORTED_ACTION);
		RETURN_STRING(MF_E_ITA_ERROR_PARSING_SAP_PARAMETERS);
		RETURN_STRING(MF_E_POLICY_MGR_ACTION_OUTOFBOUNDS);
		RETURN_STRING(MF_E_BAD_OPL_STRUCTURE_FORMAT);
		RETURN_STRING(MF_E_ITA_UNRECOGNIZED_ANALOG_VIDEO_PROTECTION_GUID);
		RETURN_STRING(MF_E_NO_PMP_HOST);
		RETURN_STRING(MF_E_ITA_OPL_DATA_NOT_INITIALIZED);
		RETURN_STRING(MF_E_ITA_UNRECOGNIZED_ANALOG_VIDEO_OUTPUT);
		RETURN_STRING(MF_E_ITA_UNRECOGNIZED_DIGITAL_VIDEO_OUTPUT);
		// Not MediaFoundation but usefull
		RETURN_STRING(S_OK);
		RETURN_STRING(S_FALSE);
		RETURN_STRING(E_FAIL);
		RETURN_STRING(E_POINTER);
		RETURN_STRING(E_UNEXPECTED);
		RETURN_STRING(E_NOTIMPL);
		RETURN_STRING(E_OUTOFMEMORY);
		RETURN_STRING(E_INVALIDARG);
		RETURN_STRING(E_NOINTERFACE);
		RETURN_STRING(E_HANDLE);
		RETURN_STRING(E_ABORT);
		RETURN_STRING(E_ACCESSDENIED);
		RETURN_STRING(E_PENDING);

    default:
						{
								HRESULT hrc = HRESULT_CODE(hr);

								switch(hrc){
				
										RETURN_STRING(ERROR_FILE_NOT_FOUND);
				      RETURN_STRING(ERROR_PATH_NOT_FOUND);
				      RETURN_STRING(ERROR_ACCESS_DENIED);
				      RETURN_STRING(ERROR_INVALID_HANDLE);
				      RETURN_STRING(ERROR_INVALID_ACCESS);
				      RETURN_STRING(ERROR_INVALID_DATA);
				      RETURN_STRING(ERROR_SYSTEM_DEVICE_NOT_FOUND);

										default:
						      return L"Unknown hresult";
								}
						}
		}
}

inline LPCWSTR MFEventString(MediaEventType evType){

		switch(evType){

				RETURN_STRING(MEError);
				RETURN_STRING(MEExtendedType);
				RETURN_STRING(MESessionTopologySet);
				RETURN_STRING(MESessionTopologiesCleared);
				RETURN_STRING(MESessionStarted);
				RETURN_STRING(MESessionPaused);
				RETURN_STRING(MESessionStopped);
				RETURN_STRING(MESessionClosed);
				RETURN_STRING(MESessionEnded);
				RETURN_STRING(MESessionRateChanged);
				RETURN_STRING(MESessionScrubSampleComplete);
				RETURN_STRING(MESessionCapabilitiesChanged);
				RETURN_STRING(MESessionTopologyStatus);
				RETURN_STRING(MESessionNotifyPresentationTime);
				RETURN_STRING(MENewPresentation);
				RETURN_STRING(MELicenseAcquisitionStart);
				RETURN_STRING(MELicenseAcquisitionCompleted);
				RETURN_STRING(MEIndividualizationStart);
				RETURN_STRING(MEIndividualizationCompleted);
				RETURN_STRING(MEEnablerProgress);
				RETURN_STRING(MEEnablerCompleted);
				RETURN_STRING(MEPolicyError);
				RETURN_STRING(MEPolicyReport);
				RETURN_STRING(MEBufferingStarted);
				RETURN_STRING(MEBufferingStopped);
				RETURN_STRING(MEConnectStart);
				RETURN_STRING(MEConnectEnd);
				RETURN_STRING(MEReconnectStart);
				RETURN_STRING(MEReconnectEnd);
				RETURN_STRING(MERendererEvent);
				RETURN_STRING(MESessionStreamSinkFormatChanged);
				RETURN_STRING(MESourceStarted);
				RETURN_STRING(MEStreamStarted);
				RETURN_STRING(MESourceSeeked);
				RETURN_STRING(MEStreamSeeked);
				RETURN_STRING(MENewStream);
				RETURN_STRING(MEUpdatedStream);
				RETURN_STRING(MESourceStopped);
				RETURN_STRING(MEStreamStopped);
				RETURN_STRING(MESourcePaused);
				RETURN_STRING(MEStreamPaused);
				RETURN_STRING(MEEndOfPresentation);
				RETURN_STRING(MEEndOfStream);
				RETURN_STRING(MEMediaSample);
				RETURN_STRING(MEStreamTick);
				RETURN_STRING(MEStreamThinMode);
				RETURN_STRING(MEStreamFormatChanged);
				RETURN_STRING(MESourceRateChanged);
				RETURN_STRING(MEEndOfPresentationSegment);
				RETURN_STRING(MESourceCharacteristicsChanged);
				RETURN_STRING(MESourceRateChangeRequested);
				RETURN_STRING(MESourceMetadataChanged);
				RETURN_STRING(MESequencerSourceTopologyUpdated);
				RETURN_STRING(MEStreamSinkStarted);
				RETURN_STRING(MEStreamSinkStopped);
				RETURN_STRING(MEStreamSinkPaused);
				RETURN_STRING(MEStreamSinkRateChanged);
				RETURN_STRING(MEStreamSinkRequestSample);
				RETURN_STRING(MEStreamSinkMarker);
				RETURN_STRING(MEStreamSinkPrerolled);
				RETURN_STRING(MEStreamSinkScrubSampleComplete);
				RETURN_STRING(MEStreamSinkFormatChanged);
				RETURN_STRING(MEStreamSinkDeviceChanged);
				RETURN_STRING(MEQualityNotify);
				RETURN_STRING(MESinkInvalidated);
				RETURN_STRING(MEAudioSessionNameChanged);
				RETURN_STRING(MEAudioSessionVolumeChanged);
				RETURN_STRING(MEAudioSessionDeviceRemoved);
				RETURN_STRING(MEAudioSessionServerShutdown);
				RETURN_STRING(MEAudioSessionGroupingParamChanged);
				RETURN_STRING(MEAudioSessionIconChanged);
				RETURN_STRING(MEAudioSessionFormatChanged);
				RETURN_STRING(MEAudioSessionDisconnected);
				RETURN_STRING(MEAudioSessionExclusiveModeOverride);
				RETURN_STRING(MEPolicyChanged);
				RETURN_STRING(MEContentProtectionMessage);
				RETURN_STRING(MEPolicySet);

		default:
				return L"Unknown event";
		}
}

inline LPCWSTR MFTopologyStatusString(MF_TOPOSTATUS status){

		switch(status){

				RETURN_STRING(MF_TOPOSTATUS_INVALID);
				RETURN_STRING(MF_TOPOSTATUS_READY);
				RETURN_STRING(MF_TOPOSTATUS_STARTED_SOURCE);
				RETURN_STRING(MF_TOPOSTATUS_DYNAMIC_CHANGED);
				RETURN_STRING(MF_TOPOSTATUS_SINK_SWITCHED);
				RETURN_STRING(MF_TOPOSTATUS_ENDED);

		default:
				return L"Unknown topology status";
		}
}

#else
  #define MFErrorString(x) L""
  #define MFEventString(x) L""
#define MFTopologyStatusString(x) L""
#endif

#endif
